version: '3.8'
networks:
  appNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.24.2.0/16"
services:
  nginx:
    image: nginxinc/nginx-unprivileged:latest
    volumes:
      - ./third_party/nginx-load-balancer/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - bouine1
      - bouine2
      - bouine3
    links:
      - bouine1
      - bouine2
      - bouine3
    ports:
      - "4000:4000"
    networks:
      appNetwork: {}
  bouine1:
    build:
      context: .
    depends_on:
      - mockingjay
    links:
      - mockingjay
    expose:
      - "8080"
      - "50051"
    ports:
      - "8081:8080"
      - "50051:50051"
    networks:
      appNetwork:
        ipv4_address: 172.24.2.1
    entrypoint: ["/app", "start", "--raft_bootstrap=true", "--raft_id=nodeA", "--raft_address=172.24.2.1:50051", "--logging_level=debug"]
  bouine2:
    build:
      context: .
    depends_on:
      - mockingjay
    links:
      - mockingjay
    expose:
      - "8080"
      - "50052"
    ports:
      - "8082:8080"
      - "50052:50052"
    networks:
      appNetwork:
        ipv4_address: 172.24.2.2
    entrypoint: ["/app", "start", "--raft_id=nodeB", "--raft_address=172.24.2.2:50052", "--logging_level=debug"]
  bouine3:
    build:
      context: .
    depends_on:
      - mockingjay
    links:
      - mockingjay
    expose:
      - "8080"
      - "50053"
    ports:
      - "8083:8080"
      - "50053:50053"
    networks:
      appNetwork:
        ipv4_address: 172.24.2.3
    entrypoint: ["/app", "start", "--raft_id=nodeC", "--raft_address=172.24.2.3:50053", "--logging_level=debug"]
  test-client:
    image: loadimpact/k6:0.37.0
    depends_on:
      - nginx
      - influxdb
      - grafana
    links:
      - nginx
      - influxdb
    networks:
      appNetwork: {}
    volumes:
      - ./third_party/k6/scenarios:/scenarios
      - ./third_party/k6/scripts:/influxdb_startup
    entrypoint: ["ash", "/influxdb_startup/entrypoint.sh", "-h", "influxdb", "-p", "8086", "-t", "5", "--", "k6"] # Tricks to wait for influxdb to be up (without custom Docker image)
  influxdb:
    image: influxdb:1.7.11
    depends_on:
      - bouine1
    ports:
      - 8086:8086
    networks:
      appNetwork: {}
  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - 3000:3000
    networks:
      appNetwork: {}
    volumes:
      - ./build/client/files/grafana:/etc/grafana
      - ./build/client/files/grafana/dashboards:/var/lib/grafana/dashboards
  mockingjay: # Mock server
    image: quii/mockingjay-server:1.12.0
    ports:
      - 8084:8084
    networks:
      appNetwork: {}
    volumes:
      - ./third_party/mockingjay-server:/config
    command: ["-config=/config/config.yaml", "-port=8084", "-debug"]
