version: "3.8"
networks:
  appNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.24.0.0/16"
services:
  bouine:
    build:
      context: .
    depends_on:
      - mockingjay
    links:
      - mockingjay
    expose:
      - "8080"
      - "50051"
    ports:
      - "8081:8080"
      - "50051:50051"
    networks:
      appNetwork:
        ipv4_address: 172.24.2.1
    entrypoint: ["/app", "start", "--logging_level=debug"]
  test-client:
    image: grafana/k6:0.49.0
    depends_on:
      - bouine
    links:
      - bouine
    networks:
      appNetwork: {}
    volumes:
      - ./third_party/k6/scenarios:/scenarios
  mockingjay: # Mock server
    image: quii/mockingjay-server:1.12.0
    ports:
      - 8084:8084
    networks:
      appNetwork: {}
    volumes:
      - ./third_party/mockingjay-server:/config
    command: ["-config=/config/config.yaml", "-port=8084", "-debug"]
