{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "bouine.fullname" . }}
  labels:
    {{- include "bouine.labels" . | nindent 4 }}
  {{- include "bouine.annotations" (list . .Values.podDisruptionBudget.annotations) | nindent 2 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "bouine.selectorLabels" . | nindent 6 }}
{{- end }}
