{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "bouine.fullname" .) }}
  labels:
    {{- include "bouine.labels" . | nindent 4 }}
  {{- include "bouine.annotations" (list . .Values.serviceAccount.annotations) | nindent 2 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
