apiVersion: v2
name: bouine
description: Cloud-native HTTP cache in Go - RFC9111 compliant, zero-alloc hit path, gossip clustering, no external K/V store.
type: application
version: 0.5.1
appVersion: "0.5.1"
icon: https://raw.githubusercontent.com/bouine-cache/bouine/main/docs/assets/logo_font.png
keywords:
  - cache
  - reverse-proxy
  - http
  - rfc9111
  - kubernetes
  - golang
  - cdn
home: https://github.com/bouine-cache/bouine
sources:
  - https://github.com/bouine-cache/bouine
maintainers:
  - name: bouine-cache
    url: https://github.com/bouine-cache
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: integration-delivery
  artifacthub.io/links: |
    - name: source
      url: https://github.com/bouine-cache/bouine
    - name: documentation
      url: https://bouine.org
    - name: container image
      url: https://hub.docker.com/r/bouinecache/bouine
  artifacthub.io/images: |
    - name: bouine
      image: docker.io/bouinecache/bouine:latest
