syntax = "proto3";

import "google/protobuf/duration.proto";

option go_package = "github.com/thylong/pkg/backend/proto";

service Cache {
  rpc AddCacheEntry(AddCacheEntryRequest) returns (AddCacheEntryResponse);
  rpc GetCacheEntry(GetCacheEntryRequest) returns (GetCacheEntryResponse);
}

message AddCacheEntryRequest {
  string cache_key = 1;
  bytes cache_entry = 2;
  google.protobuf.Duration cache_expiration = 3;
}

message AddCacheEntryResponse {
  uint64 commit_index = 1;
}

message GetCacheEntryRequest {
  string cache_key = 1;
}

message GetCacheEntryResponse {
  string cache_entry = 1;
}
