server {
    location / {
        return 200 '{"time":"$time_iso","status":"ok"}';
        add_header Content-Type application/json;
        add_header Cache-Control "public, max-age=30";
    }
    location /healthz {
        return 200;
    }
}
